services:
  # 1. Database Service
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: SmartSaudiStockAdvisor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 2. Backend
  backend:
    image: ${DOCKER_USERNAME}/smartsaudistockadvisor-backend:latest
    build: ./backend/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - app.JWT_SECRETE=${JWT_SECRETE}
      - app.JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - app-network

  # 3. Python Service
  python-service:
    image: ${DOCKER_USERNAME}/smartsaudistockadvisor-python:latest
    build: ./python/
    profiles: ["job"]
    shm_size: "1gb"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=SmartSaudiStockAdvisor
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
