name: SmartSaudiStockAdvisor Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BACKEND_DIR: "backend/SmartSaudiStockAdvisor/SmartSaudiStockAdvisor"
  PYTHON_DIR: "python/StockPredictionPy"

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BUILD BACKEND 
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_DIR }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smartsaudistockadvisor-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # BUILD PYTHON
      - name: Build and Push Python
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PYTHON_DIR }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smartsaudistockadvisor-python:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # DEPLOY TO VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd /opt/SmartSaudiStockAdvisor || mkdir -p /opt/SmartSaudiStockAdvisor && cd /opt/SmartSaudiStockAdvisor

            cat > .env << EOF
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DB_URL=jdbc:postgresql://db:5432/SmartSaudiStockAdvisor
            DB_USERNAME=postgres
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRETE=${{ secrets.JWT_SECRETE }}
            JWT_EXPIRATION_TIME=900000
            EOF

            # Download the latest docker-compose.yml
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml

            # Pull and Restart
            docker compose pull
            docker compose down
            docker compose up -d
            
            # Clean up
            docker image prune -f